//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Message", Namespace="http://schemas.datacontract.org/2004/07/BEPB.Web", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TB_Message : wcf_client.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time {
            get {
                return this.Date_TimeField;
            }
            set {
                if ((this.Date_TimeField.Equals(value) != true)) {
                    this.Date_TimeField = value;
                    this.RaisePropertyChanged("Date_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutant {
            get {
                return this.PriPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PriPollutantField, value) != true)) {
                    this.PriPollutantField = value;
                    this.RaisePropertyChanged("PriPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prompt {
            get {
                return this.PromptField;
            }
            set {
                if ((object.ReferenceEquals(this.PromptField, value) != true)) {
                    this.PromptField = value;
                    this.RaisePropertyChanged("Prompt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QLevel {
            get {
                return this.QLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.QLevelField, value) != true)) {
                    this.QLevelField = value;
                    this.RaisePropertyChanged("QLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                if ((object.ReferenceEquals(this.zoneField, value) != true)) {
                    this.zoneField = value;
                    this.RaisePropertyChanged("zone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Alert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Message))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Alert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Message))]
    public partial class EntityObject : wcf_client.ServiceReference1.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcf_client.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcf_client.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_RTC", Namespace="http://schemas.datacontract.org/2004/07/BEPB.Web", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TB_RTC : wcf_client.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> AVG24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Day8hMaxEvalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> Day8hMaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> Day8hValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DayMaxEvalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> DayMaxValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EvalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Eval24hField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriPollutantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriPollutantMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI {
            get {
                return this.AQIField;
            }
            set {
                if ((object.ReferenceEquals(this.AQIField, value) != true)) {
                    this.AQIField = value;
                    this.RaisePropertyChanged("AQI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> AVG24h {
            get {
                return this.AVG24hField;
            }
            set {
                if ((this.AVG24hField.Equals(value) != true)) {
                    this.AVG24hField = value;
                    this.RaisePropertyChanged("AVG24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time {
            get {
                return this.Date_TimeField;
            }
            set {
                if ((this.Date_TimeField.Equals(value) != true)) {
                    this.Date_TimeField = value;
                    this.RaisePropertyChanged("Date_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Day8hMaxEval {
            get {
                return this.Day8hMaxEvalField;
            }
            set {
                if ((this.Day8hMaxEvalField.Equals(value) != true)) {
                    this.Day8hMaxEvalField = value;
                    this.RaisePropertyChanged("Day8hMaxEval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Day8hMaxValue {
            get {
                return this.Day8hMaxValueField;
            }
            set {
                if ((this.Day8hMaxValueField.Equals(value) != true)) {
                    this.Day8hMaxValueField = value;
                    this.RaisePropertyChanged("Day8hMaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Day8hValue {
            get {
                return this.Day8hValueField;
            }
            set {
                if ((this.Day8hValueField.Equals(value) != true)) {
                    this.Day8hValueField = value;
                    this.RaisePropertyChanged("Day8hValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DayMaxEval {
            get {
                return this.DayMaxEvalField;
            }
            set {
                if ((this.DayMaxEvalField.Equals(value) != true)) {
                    this.DayMaxEvalField = value;
                    this.RaisePropertyChanged("DayMaxEval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> DayMaxValue {
            get {
                return this.DayMaxValueField;
            }
            set {
                if ((this.DayMaxValueField.Equals(value) != true)) {
                    this.DayMaxValueField = value;
                    this.RaisePropertyChanged("DayMaxValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Eval {
            get {
                return this.EvalField;
            }
            set {
                if ((this.EvalField.Equals(value) != true)) {
                    this.EvalField = value;
                    this.RaisePropertyChanged("Eval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Eval24h {
            get {
                return this.Eval24hField;
            }
            set {
                if ((this.Eval24hField.Equals(value) != true)) {
                    this.Eval24hField = value;
                    this.RaisePropertyChanged("Eval24h");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pollutant {
            get {
                return this.PollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PollutantField, value) != true)) {
                    this.PollutantField = value;
                    this.RaisePropertyChanged("Pollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutant {
            get {
                return this.PriPollutantField;
            }
            set {
                if ((object.ReferenceEquals(this.PriPollutantField, value) != true)) {
                    this.PriPollutantField = value;
                    this.RaisePropertyChanged("PriPollutant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutantMobile {
            get {
                return this.PriPollutantMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.PriPollutantMobileField, value) != true)) {
                    this.PriPollutantMobileField = value;
                    this.RaisePropertyChanged("PriPollutantMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QLevel {
            get {
                return this.QLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.QLevelField, value) != true)) {
                    this.QLevelField = value;
                    this.RaisePropertyChanged("QLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((object.ReferenceEquals(this.QualityField, value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Alert", Namespace="http://schemas.datacontract.org/2004/07/BEPB.Web", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TB_Alert : wcf_client.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time {
            get {
                return this.Date_TimeField;
            }
            set {
                if ((this.Date_TimeField.Equals(value) != true)) {
                    this.Date_TimeField = value;
                    this.RaisePropertyChanged("Date_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MContent {
            get {
                return this.MContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MContentField, value) != true)) {
                    this.MContentField = value;
                    this.RaisePropertyChanged("MContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wcf_client.ServiceReference1.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wcf_client.ServiceReference1.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Message[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_RTC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Alert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wcf_client.ServiceReference1.TB_Alert))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.DataService")]
    public interface DataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebCounts", ReplyAction="urn:DataService/GetWebCountsResponse")]
        string GetWebCounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebData", ReplyAction="urn:DataService/GetWebDataResponse")]
        string GetWebData();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebAlert", ReplyAction="urn:DataService/GetWebAlertResponse")]
        string GetWebAlert();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebPredict", ReplyAction="urn:DataService/GetWebPredictResponse")]
        string GetWebPredict();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/DayForecast", ReplyAction="urn:DataService/DayForecastResponse")]
        wcf_client.ServiceReference1.TB_Message[] DayForecast();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC", ReplyAction="urn:DataService/GetRTCResponse")]
        wcf_client.ServiceReference1.TB_RTC[] GetRTC();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC24h", ReplyAction="urn:DataService/GetRTC24hResponse")]
        wcf_client.ServiceReference1.TB_RTC[] GetRTC24h(string Station, string Pollutant);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetAlert", ReplyAction="urn:DataService/GetAlertResponse")]
        wcf_client.ServiceReference1.TB_Alert[] GetAlert();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceChannel : wcf_client.ServiceReference1.DataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<wcf_client.ServiceReference1.DataService>, wcf_client.ServiceReference1.DataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWebCounts() {
            return base.Channel.GetWebCounts();
        }
        
        public string GetWebData() {
            return base.Channel.GetWebData();
        }
        
        public string GetWebAlert() {
            return base.Channel.GetWebAlert();
        }
        
        public string GetWebPredict() {
            return base.Channel.GetWebPredict();
        }
        
        public wcf_client.ServiceReference1.TB_Message[] DayForecast() {
            return base.Channel.DayForecast();
        }
        
        public wcf_client.ServiceReference1.TB_RTC[] GetRTC() {
            return base.Channel.GetRTC();
        }
        
        public wcf_client.ServiceReference1.TB_RTC[] GetRTC24h(string Station, string Pollutant) {
            return base.Channel.GetRTC24h(Station, Pollutant);
        }
        
        public wcf_client.ServiceReference1.TB_Alert[] GetAlert() {
            return base.Channel.GetAlert();
        }
    }
}
